# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36ae45f9c542cca82ff75777fea20a3bcfc348a17d731a81096dfc96d5ed84acce0eb608861a6834219fabc8a5f2c2ac06c364bb6f1268bd897ba288a072693d

test:
  secret_key_base: 41040a33c232effd12313a76c8944ceba07d9e9012244efd82450617bdd8a6dd7eb13c5e3aa141634179a4e17832a21ea40fb4b33ffa5ff777bce1c6624ac0ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
